#!/bin/bash
# LeakAI Extension Installation Helper

echo "🚀 LeakAI Extension Installation Helper"
echo "======================================"
echo ""
echo "This script will help you install the LeakAI extension."
echo ""
echo "Steps:"
echo "1. Open Chrome"
echo "2. Navigate to chrome://extensions/"
echo "3. Enable 'Developer mode' (toggle in top right)"
echo "4. Click 'Load unpacked'"
echo "5. Select the 'dist' folder from this package"
echo ""
echo "The extension should now appear in your extensions list."
echo ""
echo "To verify installation:"
echo "- Click the LeakAI icon in the Chrome toolbar"
echo "- Type an email address in any text field"
echo "- You should see a colored underline appear"
echo ""
echo "For detailed instructions, see INSTALL.md"
echo ""
read -p "Press Enter to open Chrome extensions page..." 
open "chrome://extensions/" 2>/dev/null || echo "Please manually open chrome://extensions/"
